#56 Getting error in prometheus queries
Reason:
json.loads requires 'str' Type argument,
but found bytes instead. Below error is
thrown when bytes is passed.
>>> json.loads(r.content)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

Fix:
Change json.loads(r.content) to r.text)